language: python
python:
- 3.6.1
install:
- pip install -r requirements-build.txt
deploy:
  provider: heroku
  api_key:
    secure: a3fxFfgTDkUr3SPbtnTHtgydC89uDWXbWgFc7my31vssNrOKxGEN2E2yxzo/8I2DIYFayLZYKTK8QhUbvlwgao09EOEPbH1nHh70g4Uy09rcUWCtT83IOr5RVDRCGMMqAvit/rdeysKB2f0w+hU++QA7/Z9cKhWbzwaXuN19NDL6enymBHs5MUdKwmgOAvPvYD5798B+A/uG+Q0AY/CnY/j4CETGAm39zICXwq3ajIGLGPRKDwjtjaa/QdIWdIaZXNmcPmVZOvOdKh/GvBAZm4Xtb2qOcxFjAGF+R0vNduILanN5mqi/qCGprfBTqXOEorNoECA+A5CWL4SDlFS1XmnUwo8VOFtTyTX2Ph0tasLvJm9kLD16YNpD9tsTlEn1hwnA5uJ/m7yTIGoS8Mis5BluZuKhZ1huB2cDg62PWbQu0x6CXBfscoHsF+U+DERDnQNXi+jGcUKsUc+yhCktYvSPLnqEq3HU7HEvzqHhD/nUTcC7Y8jcHnWlrT+PgivvTyLaXR5RvWf+CpLylJSaGNI1xEGFJ2BwaMqpkAXu3pjgT8SMclb1zwvsMe0OGWuHfw66k2zZuwbwScyge0A2GWagWAIvJpYqYBm5ocQNg+wdyghJPVrz3SrwS/bM3RZi3xVa5vBG7n47r9Y5Hw9tQsBTf+ch+BTvW/f/2xY9omk=
  app: the-sheriff
  on:
    repo: UVA-CS3240-S19/project-102-the-sheriff
  skip_cleanup: true
script: python manage.py test housing_review
