language: python
python:
- 3.6.1
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: cPrJ5qFVQGJSul4mhlTuAsns8ziHxzjw0doNpFqiziSxT2ugcqlvU0BFsfeutLJ5Z0Bf7J6Zhu0R2eWBKK3HSBHnD09UEzsMd9EZFd8ySahCHt1c/vVsZq2wqYPA+7bdYMEnBGVfma5XzL11cjeCHMlwZB84gAjw7pbjLkcT7guUYG89N+qVGKQddUaI3W5EZpvlJ/2XS+DrSpeRamKG57FV8fsK393DMta1j4DOuHeKpzC7EH3xgvhtPgQEEGEf+NMtkZgx1H7SDhjXRixWUXSVqN6Tgbd2dXFz6BVZr+Q9/kyLUhfL7VwH4kW4MHmYNvPtysQ3RXoyFQpXV9V09YdZipMiL9i1pEbQNB/JgaoBGIuwQbtIZLXM5zund9BJCND22nUzD1cX9ZAwsPp67rw19A8DWiYgl21omKvx/I+vUmRFE3EmM2iUefO3nj00KbryTMLLe8fp7iLo1z9rw73xionkB3K1CybXIpAAyoJep87ZpIknzVFypYa4rgYfyQ4aBzV5NVFNFfq/jf6htaM/b1jd78PLqgxC/OT+JvpMqwU+cQzMrxbb27KLY00He7JR9T6OYylPlRCOVmSG15Hsy0CWZVV8RmlSzlL05IY+o4MSg/W9mokviyFstF1PXLSQeKeJo0QCZ2j5QoIFm2/qGuHc5Pd4vkW/2hfKVDM=
  app: the-sheriff
  on:
    repo: UVA-CS3240-S19/project-102-the-sheriff
script: python manage.py test housing_review
