# Generated by Django 2.1.5 on 2019-02-24 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('neighborhood', models.CharField(choices=[('Wertland', 'Wertland'), ('Rugby', 'Rugby'), ('14th Street', '14th Street'), ('JPA', 'JPA'), ('Main Street', 'Main Street')], max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('price', models.FloatField(blank=True)),
                ('parking', models.BooleanField(blank=True)),
                ('bedrooms', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('bathrooms', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pets', models.BooleanField(blank=True)),
                ('pool', models.BooleanField(blank=True)),
                ('distance_to_newcomb', models.FloatField(blank=True)),
                ('utilities_cost', models.FloatField(blank=True)),
                ('utilities_provided', models.CharField(blank=True, max_length=500)),
                ('amenities_provided', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('reviews', models.ManyToManyField(to='housing_review.Review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='housing_review.User'),
        ),
    ]
