# Generated by Django 2.1.5 on 2019-02-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
