# Generated by Django 2.1.5 on 2019-02-25 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0004_auto_20190225_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='amenities',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='bathrooms',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='bedrooms',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='distance_to_newcomb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='neighborhood',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='housing_review.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='utilities',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='utilities_cost',
            field=models.FloatField(null=True),
        ),
    ]
