# Generated by Django 2.1.7 on 2019-03-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0005_auto_20190225_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
