# Generated by Django 2.1.5 on 2019-03-30 19:10

from django.db import migrations, models
import housing_review.models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.IntegerField(default=1, validators=[housing_review.models.belongsToAUser]),
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.CharField(default='', max_length=10000, validators=[housing_review.models.lastBelongsToAReview]),
        ),
    ]
