# Generated by Django 2.1.5 on 2019-03-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
