# Generated by Django 2.1.5 on 2019-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0007_auto_20190330_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='legacy', max_length=30),
        ),
    ]
