# Generated by Django 2.1.5 on 2019-03-30 19:20

from django.db import migrations, models
import housing_review.models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0008_auto_20190330_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reviews',
            field=models.CharField(default=' ', max_length=10000, validators=[housing_review.models.lastBelongsToAReview]),
        ),
    ]
