# Generated by Django 2.1.5 on 2019-03-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0009_auto_20190330_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
    ]
