# Generated by Django 2.1.7 on 2019-04-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_review', '0010_remove_user_reviews'),
        ('housing_review', '0006_review_location'),
    ]

    operations = [
    ]
